export const INITIAL_PLANT_TYPES = {
  SUNFLOWER: {
    name: "Sunflower",
    cost: 50,
    image: "/img/sunflower.jpg",
    abilitycooldown: 7,
    hp: 150,
  },
  PEASHOOTER: {
    name: "Peashooter",
    cost: 100,
    image: "/img/peashooter.jpg",
    abilitycooldown: 1.5,
    hp: 200,
    damage: 20,
  },
  WALNUT: {
    name: "Walnut",
    cost: 50,
    image: "/img/Nut.jpg",
    abilitycooldown: 0,
    hp: 700,
  },
  POTATOMINE: {
    name: "Potato Mine",
    cost: 25,
    image: "/img/potato.jpg",
    abilitycooldown: 0,
    hp: 100,
  },
  CABBAGEPULT: {
    name: "Cabbagepult",
    cost: 150,
    image: "/img/Cabbage.jpg",
    abilitycooldown: 2,
    hp: 300,
  },
  TORCHWOOD: {
    name: "Torchwood",
    cost: 125,
    image: "/img/torch.jpg",
    abilitycooldown: 0,
    hp: 300,
  },
  SQUASH: {
    name: "Squash",
    cost: 50,
    image: "/img/squash.jpg",
    abilitycooldown: 0,
    hp: 100000,
  },
  LIGHTNINGREED: {
    name: "Lightning Reed",
    cost: 125,
    image: "/img/lightning.jpg",
    abilitycooldown: 1.5,
    hp: 300,
    damage: 15,
  },
  GATLINGPEA: {
    name: "Gatling Peashooter",
    cost: 225,
    image: "/img/gattling.jpg",
    abilitycooldown: 1.2,
    hp: 300,
    damage: 20,
  },
  CHERRYBOMB: {
    name: "Cherry Bomb",
    cost: 125,
    image: "/img/cherrybomb.jpg",
    abilitycooldown: 0,
    hp: 1,
  },
  FUMESHROOM: {
    name: "Fume Shroom",
    cost: 150,
    image: "/img/fumeshroom.jpg",
    abilitycooldown: 1,
    hp: 300,
  },
  CACTUS: {
    name: "Cactus",
    cost: 175,
    image: "/img/cactus.jpg",
    abilitycooldown: 1,
    hp: 300,
  },
  CHOMPER: {
    name: "Chomper",
    cost: 200,
    image: "/img/chomper.jpg",
    abilitycooldown: 30,
    hp: 300,
  },
  SNOWPEA: {
    name: "Snowpea",
    cost: 200,
    image: "/img/snowpea.jpg",
    abilitycooldown: 1.5,
    hp: 200,
    damage: 20,
  },
  COBCANNON: {
    name: "Cob Cannon",
    cost: 500,
    image: "/img/corn.jpg",
    abilitycooldown: 30,
    hp: 500,
  },
};

export const ZOMBIE_TYPES = {
  REGULAR: {
    name: "Regular Zombie",
    hp: 600,
    speed: 0.15,
    image: "/img/zombie.png",
    damage: 8,
  },
  CONEHEAD: {
    name: "Conehead Zombie",
    hp: 900,
    speed: 0.15,
    image: "/img/zombo.jpg",
    damage: 8,
  },
  BUCKETHEAD: {
    name: "Buckethead Zombie",
    hp: 1200,
    speed: 0.15,
    image: "/img/bucket.jpg",
    damage: 8,
  },
  QUARTERBACK: {
    name: "Quarterback Zombie",
    hp: 1500,
    speed: 0.2,
    image: "/img/quarterback.png",
    damage: 9,
  },
  JOURNALIST: {
    name: "Journalist Zombie",
    hp: 1800,
    speed: 0.15,
    image: "/img/newspaper.png",
    damage: 9,
  },
  YETI: {
    name: "Yeti",
    hp: 7000,
    speed: 0.05,
    image: "/img/yeti.jpg",
    damage: 30,
  },
  QIN_SHI_HUANG: {
    name: "Qin Shi Huang",
    hp: 15000,
    speed: 0.08,
    image: "/img/qinshi.png",
    damage: 25,
    isBoss: true,
  },
};
